package main

var (
	transmission string = "Intercepting transmission\n"
	downloading  string = "Downloading:\n"
	message      string = "This solo has been improvised from start to finish. It was take number 2 or so and we liked it so much, that we have banned Artur from redoing it. So, most likely, it will be different each time! For the nerds - that is Artur's heavily modded Fender Jazzmaster USA into Earthquaker Devices Tentacle into GodCityInstruments Baracus into Ampeg V4 into ultra-oversized Zilla 212 with V30 and Neodimium Creamback."
)

func (s *Sized) solo() {
	printInMicroseconds(transmission, halfnote)
	printInMicroseconds(downloading, quaternote)
	totalTime := halfnote + fullnote
	progressBar(100, totalTime)
	cleanDisplay()
	s.guitarSolo()
}

func (s *Sized) guitarSolo() {
	// 1st bar
	s.printNoteInBinary("D", 1678)
	s.printNoteInBinary("F", 1678)
	s.printNoteInBinary("G", 839)
	s.printNoteInBinary("A", 839)
	s.printNoteInBinary("C", 1678)
	cleanDisplay()
	// 2nd bar
	noteRest(8)
	s.printNoteInBinary("A", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("D", 210)
	s.printNoteInBinary("G", 420)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("F", 420)
	s.printNoteInBinary("F#", 210)
	s.printNoteInBinary("F", 210)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("F", 420)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("D", 420)
	s.printNoteInBinary("F", 210)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("C", 630)
	s.printNoteInBinary("E", 210)
	s.printNoteInBinary("A", 1890)
	cleanDisplay()
	// 3rd bar
	noteRest(8)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("A", 105)
	noteRest(16)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	noteRest(4)

	noteRest(8)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("E", 105)
	noteRest(16)
	noteRest(16)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	noteRest(4)

	noteRest(8)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("A", 105)
	noteRest(16)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	s.printNoteInBinary("?", 210)
	noteRest(4)

	noteRest(8)
	s.printNoteInBinary("A", 210)
	s.printNoteInBinary("G", 210)
	s.printNoteInBinary("E", 105)
	s.printNoteInBinary("G", 105)
	s.printNoteInBinary("E", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("E", 210)
	noteRest(4)
	cleanDisplay()
	// 4th bar
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("A", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("A", 105)
	s.printNoteInBinary("G#", 105)
	s.printNoteInBinary("A", 105)
	s.printNoteInBinary("G#", 105)
	s.printNoteInBinary("G", 105)
	s.printNoteInBinary("G#", 105)
	s.printNoteInBinary("G", 105)
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("G", 105)

	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("A", 105)
	s.printNoteInBinary("G#", 105)
	s.printNoteInBinary("G", 105)
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("C", 105)
	s.printNoteInBinary("D", 105)
	s.printNoteInBinary("F", 105)
	s.printNoteInBinary("G", 105)
	cleanDisplay()
	printBinaryInMicroseconds(message, 1678)
	noteRest(2)
	noteRest(4)
	cleanDisplay()
}
