package main

import (
	"fmt"
	"time"
)

func verse2() {
	cleanDisplay()
	printFrame(frame1, quaternote)
	printFrame(frame2, halfnote)
	printFrame(frame3, halfnote)
	printFrame(frame4, halfnote)
	printFrame(frame5, halfnote)
	printFrame(frame6, halfnote)
	printFrame(frame7, halfnote)
	printFrame(frame8, halfnote)
	printFrame(frame9, halfnote)
	printFrame(frame10, halfnote)
	printFrame(frame11, halfnote)
	printFrame(frame12, halfnote)
	printFrame(frame13, halfnote)
	printFrame(frame14, halfnote)
	printFrame(frame15, halfnote)
	printFrame(frame16, halfnote)
	printFrame(frame17, halfnote)
	printFrame(frame18, halfnote)
	printFrame(frame19, halfnote)
	printFrame(frame20, halfnote)
	printFrame(frame21, halfnote)
	printFrame(frame22, halfnote)
	printFrame(frame23, halfnote)
	printFrame(frame24, halfnote)
	printFrame(frame25, halfnote)
	printFrame(frame26, halfnote)
	printFrame(frame27, halfnote)
	printFrame(frame28, halfnote)
	printFrame(frame29, eightnote)
	printFrame(frame30, eightnote)
	printFrame(frame31, eightnote)
	printFrame(frame32, eightnote)
	printFrame(frame33, eightnote)
	printFrame(frame34, eightnote)
	printFrame(frame35, eightnote)
	printFrame(frame36, eightnote)
	printFrame(frame37, eightnote)
	printFrame(frame38, eightnote)
	printFrame(frame39, sixteenthnote)
	printFrame(frame40, sixteenthnote)
	printFrame(frame41, sixteenthnote)
	printFrame(frame42, sixteenthnote)
	printFrame(frame43, sixteenthnote)
	printFrame(frame44, sixteenthnote)
	colourTextRGB(255, 255, 153)
	printFrame(frame45, sixteenthnote)
	colourTextRGB(255, 255, 0)
	printFrame(frame46, sixteenthnote)
	colourTextRGB(255, 255, 0)
	printFrame(frame47, sixteenthnote)
	colourTextRGB(255, 51, 0)
	printFrame(frame48, eightnote)
	colourTextRGB(255, 0, 0)
	printFrame(frame49, eightnote)
	colourTextRGB(255, 204, 204)
	printFrame(frame50, eightnote)
	resetColourChanges()
	printFrame(frame51, eightnote)
}

func printFrame(frame string, wait int) {
	fmt.Printf("%v", frame)
	time.Sleep(time.Millisecond * time.Duration(wait))
	cleanDisplay()
}
